version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: kaliss-db
    environment:
      - POSTGRES_DB=corebanking
      - POSTGRES_USER=corebanking
      - POSTGRES_PASSWORD=corebanking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - kaliss-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U corebanking -d corebanking"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ibrahimkelly/kaliss-backend:latest
    container_name: kaliss-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/corebanking
      - SPRING_DATASOURCE_USERNAME=corebanking
      - SPRING_DATASOURCE_PASSWORD=corebanking
      - KALISS_LICENSE_KEY=${KALISS_LICENSE_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kaliss-net

  frontend:
    image: ibrahimkelly/kaliss-frontend:latest
    container_name: kaliss-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - kaliss-net

volumes:
  pgdata:

networks:
  kaliss-net:
    driver: bridge
