name: Build macOS DMG

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger build when pushing tags like v1.0.0, v1.0.1, etc.

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      # 1. Checkout the Electron code (this repository)
      - name: Checkout Electron Code
        uses: actions/checkout@v4

      # 2. Checkout the Java Backend repository
      - name: Checkout Backend Code
        uses: actions/checkout@v4
        with:
          repository: thltechnologies/Core-Banking-Backend
          ref: 1200-setup-tests-environnement-for-users-and-clients
          path: Core-Banking-Backend
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      # 2b. Checkout the Angular Dashboard repository
      - name: Checkout Dashboard Code
        uses: actions/checkout@v4
        with:
          repository: thltechnologies/Core-Banking-Dashboard-Angular
          ref: 997-setup-tests-environnement-for-users-and-clients
          path: Core-Banking-Dashboard-Angular
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Build Angular Dashboard
        run: |
          cd Core-Banking-Dashboard-Angular
          npm install
          npm run build

      - name: Copy Dashboard Build to Backend Static Resources
        run: |
          rm -rf Core-Banking-Backend/src/main/resources/static/*
          mkdir -p Core-Banking-Backend/src/main/resources/static
          cp -r Core-Banking-Dashboard-Angular/dist/corebanking-ng/* Core-Banking-Backend/src/main/resources/static/

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Java Backend JAR
        run: |
          cd Core-Banking-Backend
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          cp target/corebanking-0.0.1-SNAPSHOT.jar ../corebanking-testing.jar

      - name: Build Electron App (macOS DMG)
        run: |
          npm install
          npx electron-builder --mac dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Conserver le fichier DMG généré dans les Artifacts GitHub
      - name: Upload macOS DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: THL-KALIX-1.0.0
          path: dist/*.dmg  # Récupère tous les fichiers .dmg générés dans le dossier de build par défaut